### ISSUE TITLE
ForcesArchive PAC File Saving

### ISSUE THREAD

**Issue by Radfordhound** [Radfordhound/HedgeLib#29]
like
dude

come on
seriously??

**Comment by blueskythlikesclouds** [comment]
mood

**Comment by blueskythlikesclouds** [comment]
This was the exact issue I had back when I first made SFPac.
I can't check the code right now, but I'm assuming you're reading the child nodes in a for loop, using the node's child count?
In that case, *don't*.
If you do that, most of the terrain models are gonna have incorrect names because of the way the nodes were read, so you should read nodes with the child indices given in the model file. This should fix it.

**Comment by Radfordhound** [comment]
NANI HOW DID I MISS A COMMENT ON A GITHUB ISSUE TOO?!!? HOLY FRICK I'M TERRIBLE

Welp Skyth DM'd me about this. Turns out it wasn't a bug with ForcesArchive.cs, rather a bug in an old version of SFPac I was using that sometimes resulted in extracted file names being incorrect. I used an older SFPac to extract this sector before repacking it with HedgeLib as a test, so there you go. It was actually repacking correctly. Tried this again today except with a folder extracted by the newest SFPac rather than the old version and the sector loads in-game.

Haven't seen any bugs other than this thus far so I'm gonna close this. If anyone finds another bug feel free to open a new issue.
