### ISSUE TITLE
Clicking on the Development Build download doesn't seem to work?

### ISSUE THREAD

**Issue by Shodance** [Radfordhound/HedgeLib#75]
On the stable release it continues to a proper download, but the Dev build goes to what seems like an error report 
![image](https://user-images.githubusercontent.com/40772985/201235059-42b5f277-4d78-4e3c-b4ae-5f06dc96616b.png)

**Comment by Radfordhound** [comment]
Hi, yes, the AppVeyor build is currently failing for everything but 64-bit Windows.

It appears the 32-bit Windows build is failing due to a code error on my part involving the Vulkan API, while the rest are failing due to sudden breaking changes made to various third-party packages/configurations/etc. outside of my control that broke my perfectly fine builds yet again with no warning. I plan to fix the AppVeyor builds in the short-term and switch to GitHub Actions in the long-term to hopefully make these breaking build changes occur less frequently, since keeping up with them changing constantly has honestly been very difficult for me.

In the meantime, the 64-bit Windows build appears to have succeeded, so you can simply download and use that if you're on Windows, or build the code manually if you're on another platform. I'll close this issue once I fix the other builds.

**Comment by Shodance** [comment]
How do you download it...?

**Comment by Radfordhound** [comment]
Finally got time to fix this! 5e3cb21adb6efdfa097b625c8417eaaacd45fcfc
